# Generated by Django 2.2.16 on 2022-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient_1', models.FloatField(blank=True, null=True)),
                ('coefficient_2', models.FloatField(blank=True, null=True)),
                ('coefficient_3', models.FloatField(blank=True, null=True)),
                ('root_1', models.FloatField(blank=True, null=True)),
                ('root_2', models.FloatField(blank=True, null=True)),
                ('answer', models.CharField(max_length=30)),
            ],
        ),
    ]
