version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python quadratic_equation/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    env_file:
      - ./.env
    ports:
      - '0.0.0.0:8000:8000'
    depends_on:
      - db
